### ISSUE TITLE
大佬，可以出个没有utdid的版本吗

### ISSUE THREAD

**Issue by qewqewzzz** [RxReader/alipay_kit#18]
大佬，同时引用这个插件和友盟的，会发生utdid冲突的

**Comment by v7lin** [comment]
晚上弄

**Comment by v7lin** [comment]
Android 还是 iOS ？

**Comment by qewqewzzz** [comment]
Android和iOS都要，希望大佬帮帮忙，本人非原生开发的菜鸡实在改不来，感谢

**Comment by v7lin** [comment]
```groovy
buildscript {
    ext.alipay_kit_flavor = "noutdid" // 默认 "utdid"
}
```

```Podfile
$AlipayKitSubspec = 'noutdid' # 默认 utdid
```

```yaml
dependencies:
  alipay_kit: ^4.0.0 # 默认不包含iOS支付
  alipay_kit_android: ^4.0.1 # Android支付
  alipay_kit_ios: ^4.0.1 # iOS支付
```
