### ISSUE TITLE
gradle编译错误

### ISSUE THREAD

**Issue by tom0gao** [rxreader/alipay_kit#20]
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :alipay_kit project caused this error: /Users/hhyy/.pub-cache/hosted/pub.flutter-io.cn/alipay_kit-1.1.0/android/libs/alipaySdk-15.7.6-20200521195109.aar

**Comment by v7lin** [comment]
不建议将 gradle 升级到 4.x 版本，官方目前的 gradle 在 4.x 上有兼容问题

**Comment by tom0gao** [comment]
目前在源码中把配置修改为
// v15.7.6
compileOnly fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
然后把aar拷进自己项目
implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

**Comment by v7lin** [comment]
alipay_kit: ^1.1.1 发布前的检查项还没时间去弄，先用 git 方式吧
```
dependencies:
  alipay_kit:
    git:
      url: https://github.com/v7lin/alipay_kit.git
      ref: 993d88c8a42236e262c0ebc38caf5cdb1ecd84c0
```
